import { z } from 'zod';
import { dispatch } from './dispatch';
import * as s from './schemas';
import type * as t from './types';
import { decodeResponse } from './validation';
import { AppErrorException } from './errors';
const call = async <T>(command: string, schema: z.ZodType<T>, args?: unknown, requestSchema?: z.ZodType<unknown>): Promise<T> => { if (requestSchema) { const parsed = requestSchema.safeParse(args); if (!parsed.success) throw new AppErrorException({ code: 'profile_invalid', operation: command, subjectId: null, message: `Invalid arguments for ${command}`, details: parsed.error.issues.map(i => `${i.path.join('.')}: ${i.message}`).join('; ').slice(0, 500), retryable: false }); } return decodeResponse(schema, await dispatch(command, args), command); };
export const listProfiles = () => call('list_profiles', s.profileSummarySchema.array(), undefined, z.undefined());
export const getProfile = (profileId: string) => call('get_profile', s.profileDetailsSchema, { profileId }, s.profileIdRequestSchema);
export const inspectProfileDraft = (draft: t.ProfileDraft) => call('inspect_profile_draft', s.profileValidationSchema, draft, s.profileDraftSchema);
export const createProfile = (draft: t.ProfileDraft) => call('create_profile', s.profileSummarySchema, draft, s.profileDraftSchema);
export const updateProfile = (request: t.UpdateProfileRequest) => call('update_profile', s.profileSummarySchema, request, s.updateProfileRequestSchema);
export const removeProfile = (request: t.RemoveProfileRequest) => call('remove_profile', s.unitSchema, request, s.removeProfileRequestSchema);
export const getRuntimeState = () => call('get_runtime_state', s.runtimeStateSchema, undefined, z.undefined());
export const connectRuntime = () => call('connect_runtime', s.runtimeStateSchema, undefined, z.undefined());
export const getProjectStatus = (profileId: string) => call('get_project_status', s.projectStatusSchema, { profileId }, s.profileIdRequestSchema);
export const getInventory = () => call('get_inventory', s.inventorySchema, undefined, z.undefined());
export const refreshInventory = () => call('refresh_inventory', s.inventorySchema, undefined, z.undefined());
export const getProjectDetails = (profileId: string) => call('get_project_details', s.projectDetailsResponseSchema, { profileId }, s.profileIdRequestSchema);
export const refreshProjectDefinition = (profileId: string) => call('refresh_project_definition', s.projectDefinitionSchema, { profileId }, s.profileIdRequestSchema);
const lifecycle = (command: string, profileId: string) => call(command, s.lifecycleResultSchema, { profileId }, s.profileIdRequestSchema);
export const applyProject = (profileId: string) => lifecycle('apply_project', profileId);
export const stopProject = (profileId: string) => lifecycle('stop_project', profileId);
export const tearDownProject = (profileId: string) => lifecycle('tear_down_project', profileId);
export const restartProject = (profileId: string) => lifecycle('restart_project', profileId);
