import { z } from 'zod';
import { dispatch } from './dispatch';
import * as s from './schemas';
import type * as t from './types';
import { decodeResponse } from './validation';
const call = <T>(command: string, schema: z.ZodType<T>, args?: unknown): Promise<T> => dispatch(command, args).then(raw => decodeResponse(schema, raw, command));
export const listProfiles = () => call('list_profiles', s.profileSummarySchema.array());
export const getProfile = (profileId: string) => call('get_profile', s.profileDetailsSchema, { profileId });
export const inspectProfileDraft = (draft: t.ProfileDraft) => call('inspect_profile_draft', s.profileValidationSchema, draft);
export const createProfile = (draft: t.ProfileDraft) => call('create_profile', s.profileSummarySchema, draft);
export const updateProfile = (request: t.UpdateProfileRequest) => call('update_profile', s.profileSummarySchema, request);
export const removeProfile = (request: t.RemoveProfileRequest) => call('remove_profile', s.unitSchema, request);
export const getRuntimeState = () => call('get_runtime_state', s.runtimeStateSchema);
export const connectRuntime = () => call('connect_runtime', s.runtimeStateSchema);
export const getProjectStatus = (profileId: string) => call('get_project_status', s.projectStatusSchema, { profileId });
const lifecycle = (command: string, profileId: string) => { if (typeof profileId !== 'string') throw new TypeError('profileId required'); return call(command, s.lifecycleResultSchema, { profileId }); };
export const applyProject = (profileId: string) => lifecycle('apply_project', profileId);
export const stopProject = (profileId: string) => lifecycle('stop_project', profileId);
export const tearDownProject = (profileId: string) => lifecycle('tear_down_project', profileId);
export const restartProject = (profileId: string) => lifecycle('restart_project', profileId);
