import { z } from 'zod';
import { appErrorSchema, appErrorSubjectSchema, errorCodeSchema } from './errors';
const uuid = z.string().uuid().refine(value => value === value.toLowerCase() && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value), 'must be canonical lowercase hyphenated UUID'); const revision = z.number().int().nonnegative(); const timestamp = z.string().datetime({ offset: true });
export { appErrorSchema };
export const registrationOriginSchema = z.enum(['manual','discovered','migrated']);
export const issueSchema = z.object({ field: z.string().nullable().optional(), message: z.string() });
export const profileSummarySchema = z.object({ id: uuid, revision, displayName: z.string(), composeProjectName: z.string(), workingDirectory: z.string(), registrationOrigin: registrationOriginSchema });
export const profileDraftSchema = z.object({ displayName: z.string(), composeProjectName: z.string(), workingDirectory: z.string(), composeFiles: z.array(z.string()), environmentFiles: z.array(z.string()) });
export const profilePatchSchema = profileDraftSchema;
export const profileDetailsSchema = z.object({ profile: profileSummarySchema, composeFiles: z.array(z.string()), environmentFiles: z.array(z.string()) });
export const profileValidationSchema = z.object({ valid: z.boolean(), issues: z.array(issueSchema) });
export const updateProfileRequestSchema = z.object({ profileId: uuid, expectedRevision: z.number().int().nonnegative(), patch: profilePatchSchema });
export const removeProfileRequestSchema = z.object({ profileId: uuid, expectedRevision: z.number().int().nonnegative() });
export const profileIdRequestSchema = z.object({ profileId: uuid }).strict();
export const daemonFingerprintSchema = z.object({ daemonId: z.string(), serverVersion: z.string(), osType: z.string(), architecture: z.string() });
export const sessionContextSchema = z.object({ sessionId: uuid, endpoint: z.string(), daemonFingerprint: daemonFingerprintSchema, connectedAt: timestamp });
export const mismatchDetailsSchema = z.object({ endpoint: z.string(), apiFingerprint: daemonFingerprintSchema, cliFingerprint: daemonFingerprintSchema });
export const runtimeStateSchema = z.discriminatedUnion('state', [z.object({state:z.literal('disconnected')}),z.object({state:z.literal('connecting')}),z.object({state:z.literal('ready'),context:sessionContextSchema}),z.object({state:z.literal('contextMismatch'),details:mismatchDetailsSchema}),z.object({state:z.literal('failed'),error:appErrorSchema})]);
export const runtimeProjectionSchema = z.object({presence:z.enum(['unavailable','absent','present']),activity:z.enum(['all-running','mixed','none-running']).nullable().optional(),containerCount:z.number().int().nonnegative(),runningContainerCount:z.number().int().nonnegative(),observedAt:timestamp.nullable().optional()});
export const projectStatusSchema = z.object({profileId:uuid,runtime:runtimeProjectionSchema,definition:z.object({state:z.enum(['unchecked','valid','invalid','stale']),revision:z.string().nullable().optional(),serviceCount:z.number().int().nonnegative().nullable().optional()}),operation:z.object({kind:z.enum(['apply','stop','tear-down','restart']),phase:z.enum(['queued','running','succeeded','failed']),startedAt:timestamp}).nullable().optional(),issues:z.array(issueSchema)}).superRefine((status, ctx) => { if (status.runtime.presence !== 'present' && (status.runtime.activity != null || status.runtime.observedAt != null)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['runtime'], message: 'unavailable or absent runtime cannot include activity or observedAt' }); });
export const containerStateSchema = z.enum(['running', 'stopped', 'unknown']);
export const inventoryFreshnessSchema = z.enum(['fresh', 'stale', 'unavailable']);
export const portBindingActionSchema = z.object({ copy: z.string(), url: z.string().nullable().optional() });
export const portBindingSchema = z.object({ hostIp: z.string().nullable().optional(), hostPort: revision.nullable().optional(), containerPort: revision, protocol: z.string(), action: portBindingActionSchema });
export const containerInstanceSchema = z.object({ id: z.string(), name: z.string(), image: z.string(), state: containerStateSchema, statusText: z.string(), serviceName: z.string().nullable().optional(), publishedPorts: portBindingSchema.array() });
export const projectRuntimeSnapshotSchema = z.object({ composeProjectName: z.string(), workingDirectory: z.string().nullable().optional(), configFiles: z.string().array(), containers: containerInstanceSchema.array() });
export const composeObservationGroupSchema = z.object({ composeProjectName: z.string(), workingDirectory: z.string().nullable().optional(), configFiles: z.string().array(), containerIds: z.string().array() });
export const inventorySchema = z.object({ generation: revision, hasSnapshot: z.boolean(), observedAt: timestamp.nullable().optional(), runtimeSessionId: uuid.nullable().optional(), daemonFingerprint: daemonFingerprintSchema.nullable().optional(), freshness: inventoryFreshnessSchema, lastSuccessfulObservedAt: timestamp.nullable().optional(), containers: containerInstanceSchema.array(), projects: projectRuntimeSnapshotSchema.array(), composeObservationGroups: composeObservationGroupSchema.array(), standaloneContainers: containerInstanceSchema.array(), error: appErrorSchema.nullable().optional() }).superRefine((value, ctx) => {
  if (!value.hasSnapshot && (value.generation !== 0 || value.freshness !== 'unavailable' || value.containers.length !== 0 || value.projects.length !== 0 || value.composeObservationGroups.length !== 0 || value.standaloneContainers.length !== 0 || value.observedAt != null || value.lastSuccessfulObservedAt != null || value.runtimeSessionId != null || value.daemonFingerprint != null)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['hasSnapshot'], message: 'pre-observation inventory must be empty and unavailable' });
  if (value.hasSnapshot && value.generation < 1) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['generation'], message: 'published inventory generation must be positive' });
});
export const serviceDefinitionSchema = z.object({ name: z.string(), image: z.string().nullable().optional(), buildContext: z.string().nullable().optional(), declaredPorts: z.string().array() });
export const projectDefinitionSchema = z.object({profileId:uuid,definitionRevision:z.string().nullable().optional(),loadedAt:timestamp.nullable().optional(),state:z.enum(['unchecked','valid','invalid','stale']),services:serviceDefinitionSchema.array(),issues:z.array(issueSchema),error:appErrorSchema.nullable().optional()});
export const projectDetailsResponseSchema = z.object({profile:profileDetailsSchema,definition:projectDefinitionSchema,runtime:runtimeProjectionSchema});
export const lifecycleResultWithInventorySchema = z.object({profileId:uuid,success:z.boolean(),inventoryGeneration:z.number().int().nonnegative(),inventory:inventorySchema}).superRefine((value, ctx) => { if (value.inventoryGeneration !== value.inventory.generation) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['inventoryGeneration'], message: 'must match inventory.generation' }); });
export { lifecycleResultWithInventorySchema as lifecycleResultSchema };
export const unitSchema = z.union([z.undefined(), z.null(), z.object({}).strict()]).transform(() => undefined);

const sha256 = z.string().regex(/^[0-9a-f]{64}$/);
export const discoveryClassificationSchema = z.enum(['new_unambiguous', 'name_conflict', 'incomplete_metadata', 'already_registered']);
export const discoveryConflictSourceSchema = z.enum(['runtime_observation', 'registered_profile']);
export const discoveryConflictEvidenceSchema = z.object({ source: discoveryConflictSourceSchema, profileId: uuid.nullable().default(null), workingDirectory: z.string().nullable().optional(), configFiles: z.string().array() });
export const registerCandidateRequestSchema = z.object({ candidateId: sha256, runtimeSessionId: uuid, inventoryGeneration: revision, composeProjectName: z.string(), workingDirectory: z.string().nullable().optional(), configFiles: z.string().array() }).strict();
export const discoveryCandidateSchema = registerCandidateRequestSchema.extend({ containerCount: revision, classification: discoveryClassificationSchema, conflicts: discoveryConflictEvidenceSchema.array(), ignored: z.boolean() }).strip();
export const discoveryListSchema = z.object({ candidates: discoveryCandidateSchema.array(), autoRegistrationEnabled: z.boolean() });
export const ignoreCandidateRequestSchema = z.object({ candidateId: sha256 }).strict();
export const configureAutoRegistrationRequestSchema = z.object({ enabled: z.boolean() }).strict();
export const autoRegistrationConfigurationSchema = z.object({ enabled: z.boolean() });
export const autoRegistrationResultSchema = z.object({ profiles: profileSummarySchema.array(), errors: appErrorSchema.array() });
export const autoRegistrationRequestSchema = z.object({ runtimeSessionId: uuid, inventoryGeneration: revision }).strict();

export const registrySnapshotIdentitySchema = z.object({ registryRevision: revision, canonicalContentSha256: sha256 });
export const registryHealthStateSchema = z.enum(['healthy', 'missing', 'corrupt', 'unreadable', 'locked', 'write_failure']);
export const registryHealthSchema = z.object({ state: registryHealthStateSchema, identity: registrySnapshotIdentitySchema.nullable().optional(), error: appErrorSchema.nullable().optional(), lastOperationAt: timestamp.nullable().default(null), lastFailureAt: timestamp.nullable().default(null) });
export const runtimeDiagnosticsSchema = z.object({ state: runtimeStateSchema, resolvedEndpoint: z.string().nullable().optional(), apiFingerprint: daemonFingerprintSchema.nullable().optional(), cliFingerprint: daemonFingerprintSchema.nullable().optional(), sessionId: uuid.nullable().default(null), connectedAt: timestamp.nullable().default(null) });
export const recoveryResultSchema = z.object({ success: z.boolean(), error: appErrorSchema.nullable().optional() });
export const backupValidationStateSchema = z.enum(['missing', 'valid', 'corrupt', 'unreadable']);
export const registryBackupDiagnosticsSchema = z.object({ exists: z.boolean(), modifiedAt: timestamp.nullable().default(null), state: backupValidationStateSchema, error: appErrorSchema.nullable().optional() });
export const registryDiagnosticsSchema = z.object({ registryPath: z.string(), backupPath: z.string(), backup: registryBackupDiagnosticsSchema, revision: revision.nullable().optional(), health: registryHealthSchema, lockTimeoutMs: revision, lastRecoveryResult: recoveryResultSchema.nullable().optional() });
export const importDiagnosticsSchema = z.object({ sourcePath: z.string(), importedCount: revision, sourcePreserved: z.boolean(), error: appErrorSchema.nullable().optional() });
export const activeOperationPhaseSchema = z.enum(['pending', 'active']);
export const activeOperationSchema = z.object({ kind: z.string(), subjectId: z.string(), startedAt: timestamp, phase: activeOperationPhaseSchema });
export const operationsDiagnosticsSchema = z.object({ generation: revision, active: activeOperationSchema.array() });
export const profileDefinitionDiagnosticsSchema = z.object({ profileId: uuid, definition: projectDefinitionSchema.nullable().optional(), error: appErrorSchema.nullable().optional() });
export const definitionsDiagnosticsSchema = z.object({ generation: revision, profiles: profileDefinitionDiagnosticsSchema.array() });
export const journalEventKindSchema = z.enum(['connect_started', 'connect_succeeded', 'connect_failed', 'disconnect_started', 'disconnect_succeeded', 'disconnect_failed', 'reconnect_started', 'reconnect_succeeded', 'reconnect_failed', 'manual_registration_started', 'manual_registration_succeeded', 'manual_registration_failed', 'auto_registration_started', 'auto_registration_succeeded', 'auto_registration_failed', 'backup_started', 'backup_succeeded', 'backup_failed', 'restore_started', 'restore_succeeded', 'restore_failed', 'profile_lifecycle_started', 'profile_lifecycle_succeeded', 'profile_lifecycle_failed', 'container_action_started', 'container_action_succeeded', 'container_action_failed', 'candidate_ignored']);
export const journalSeveritySchema = z.enum(['info', 'error']);
export const journalEntrySchema = z.object({ sequence: revision, timestamp, runtimeSessionId: uuid.nullable().default(null), kind: journalEventKindSchema, severity: journalSeveritySchema, subject: appErrorSubjectSchema.nullable().optional(), errorCode: errorCodeSchema.nullable().optional(), message: z.string().max(500) });
export const sessionJournalSchema = z.object({ entries: journalEntrySchema.array() });
export const diagnosticsSnapshotSchema = z.object({ runtime: runtimeDiagnosticsSchema, registry: registryDiagnosticsSchema, import: importDiagnosticsSchema, operations: operationsDiagnosticsSchema, inventory: inventorySchema, definitions: definitionsDiagnosticsSchema, journal: sessionJournalSchema });
export const applicationStateScopeSchema = z.enum(['profiles', 'discovery', 'diagnostics', 'runtime', 'definitions']);
export const applicationStateChangedSchema = z.object({ sequence: revision, scopes: applicationStateScopeSchema.array() });

export const containerActionSchema = z.enum(['start', 'stop', 'restart']);
export const containerActionObservationSchema = z.enum(['confirmed_in_session', 'indeterminate_after_session_change']);
export const containerLogsRequestSchema = z.object({ containerId: z.string(), runtimeSessionId: uuid }).strict();
export const containerActionRequestSchema = containerLogsRequestSchema.extend({ action: containerActionSchema });
export const containerActionResultSchema = z.object({ containerId: z.string(), action: containerActionSchema, observation: containerActionObservationSchema, inventory: inventorySchema });
export const containerLogsSchema = z.object({ containerId: z.string(), text: z.string(), retainedBytes: revision.max(262144), truncated: z.boolean(), observedAt: timestamp });
export const openContainerPortRequestSchema = containerLogsRequestSchema.extend({ bindingIndex: revision });
export const reconnectResultSchema = z.object({ runtimeState: runtimeStateSchema, inventory: inventorySchema.nullable().optional() });
