import { z } from 'zod';
import { appErrorSchema } from './errors';
const uuid = z.string().uuid().refine(value => value === value.toLowerCase() && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value), 'must be canonical lowercase hyphenated UUID'); const revision = z.number().int().nonnegative(); const timestamp = z.string().datetime({ offset: true });
export { appErrorSchema };
export const registrationOriginSchema = z.enum(['manual','discovered','migrated']);
export const issueSchema = z.object({ field: z.string().nullable().optional(), message: z.string() });
export const profileSummarySchema = z.object({ id: uuid, revision, displayName: z.string(), composeProjectName: z.string(), workingDirectory: z.string(), registrationOrigin: registrationOriginSchema });
export const profileDraftSchema = z.object({ displayName: z.string(), composeProjectName: z.string(), workingDirectory: z.string(), composeFiles: z.array(z.string()), environmentFiles: z.array(z.string()) });
export const profilePatchSchema = profileDraftSchema;
export const profileDetailsSchema = z.object({ profile: profileSummarySchema, composeFiles: z.array(z.string()), environmentFiles: z.array(z.string()) });
export const profileValidationSchema = z.object({ valid: z.boolean(), issues: z.array(issueSchema) });
export const updateProfileRequestSchema = z.object({ profileId: uuid, expectedRevision: z.number().int().nonnegative(), patch: profilePatchSchema });
export const removeProfileRequestSchema = z.object({ profileId: uuid, expectedRevision: z.number().int().nonnegative() });
export const profileIdRequestSchema = z.object({ profileId: uuid });
export const daemonFingerprintSchema = z.object({ daemonId: z.string(), serverVersion: z.string(), osType: z.string(), architecture: z.string() });
export const sessionContextSchema = z.object({ sessionId: uuid, endpoint: z.string(), daemonFingerprint: daemonFingerprintSchema, connectedAt: timestamp });
export const mismatchDetailsSchema = z.object({ endpoint: z.string(), apiFingerprint: daemonFingerprintSchema, cliFingerprint: daemonFingerprintSchema });
export const runtimeStateSchema = z.discriminatedUnion('state', [z.object({state:z.literal('disconnected')}),z.object({state:z.literal('connecting')}),z.object({state:z.literal('ready'),context:sessionContextSchema}),z.object({state:z.literal('contextMismatch'),details:mismatchDetailsSchema}),z.object({state:z.literal('failed'),error:appErrorSchema})]);
export const runtimeProjectionSchema = z.object({presence:z.enum(['unavailable','absent','present']),activity:z.enum(['all-running','mixed','none-running']).nullable().optional(),containerCount:z.number().int().nonnegative(),runningContainerCount:z.number().int().nonnegative(),observedAt:timestamp.nullable().optional()});
export const projectStatusSchema = z.object({profileId:uuid,runtime:runtimeProjectionSchema,definition:z.object({state:z.enum(['unchecked','valid','invalid','stale']),revision:z.string().nullable().optional(),serviceCount:z.number().int().nonnegative().nullable().optional()}),operation:z.object({kind:z.enum(['apply','stop','tear-down','restart']),phase:z.enum(['queued','running','succeeded','failed']),startedAt:timestamp}).nullable().optional(),issues:z.array(issueSchema)}).superRefine((status, ctx) => { if (status.runtime.presence !== 'present' && (status.runtime.activity != null || status.runtime.observedAt != null)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['runtime'], message: 'unavailable or absent runtime cannot include activity or observedAt' }); });
export const lifecycleResultSchema = z.object({profileId:uuid,success:z.boolean()});
export const unitSchema = z.union([z.undefined(), z.null(), z.object({}).strict()]).transform(() => undefined);
