import { firefox } from '@playwright/test';

const browser = await firefox.launch({ headless: true });
const failureContext = await browser.newContext();
const failurePage = await failureContext.newPage();
await failurePage.goto(`${process.argv[2]}/`, { waitUntil: 'networkidle' });
await failurePage.getByRole('button', { name: /add project/i }).click();
await failurePage.getByLabel('Display name').fill('Existing Project');
await failurePage.getByLabel('Compose name').fill('existing');
await failurePage.getByLabel('Working directory').fill('/tmp/existing');
await failurePage.getByRole('button', { name: 'Next' }).click();
await failurePage.getByRole('button', { name: 'Save', exact: true }).click();
await failurePage.getByText('Existing Project').waitFor();
await failurePage.goto(`${process.argv[2]}/?runtimeFailure`, { waitUntil: 'networkidle' });
await failurePage.getByText('Existing Project').waitFor();
if (!await failurePage.getByText('runtime offline').isVisible()) throw new Error('runtime failure was not visible');
await failureContext.close();
const lifecycleContext = await browser.newContext();
const page = await lifecycleContext.newPage();
await page.goto(`${process.argv[2]}/?lifecycle`, { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /add project/i }).click();
await page.getByLabel('Display name').fill('Smoke Project');
await page.getByLabel('Compose name').fill('smoke');
await page.getByLabel('Working directory').fill('/tmp/smoke');
await page.getByRole('button', { name: 'Next' }).click();
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.getByText('Smoke Project').waitFor();
await page.getByRole('button', { name: /edit smoke project/i }).click();
await page.getByLabel('Display name').fill('Edited Project');
await page.getByRole('button', { name: 'Next' }).click();
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.getByText('Edited Project').waitFor();
await page.getByRole('button', { name: /more actions/i }).click();
await page.getByRole('menuitem', { name: 'Tear down' }).click();
await page.getByRole('button', { name: 'Tear down' }).click();
await page.getByText('Edited Project').waitFor();
await page.getByRole('button', { name: /more actions/i }).click();
await page.getByRole('menuitem', { name: 'Apply' }).click();
await page.getByRole('button', { name: 'Stop' }).click();
await page.getByRole('button', { name: 'Restart' }).click();
await page.getByRole('button', { name: /more actions/i }).click();
await page.getByRole('menuitem', { name: 'Remove profile' }).click();
await page.getByRole('button', { name: /^Cancel$/ }).click();
await page.getByText('Edited Project').waitFor();
const beforeRemove = await page.evaluate(() => (window.__COLUI_MOCK_INVOCATIONS ?? []).filter(invocation => invocation.command === 'remove_profile').length);
if (beforeRemove !== 0) throw new Error('remove_profile invoked while confirmation was canceled');
await page.getByRole('button', { name: /more actions/i }).click();
await page.getByRole('menuitem', { name: 'Remove profile' }).click();
await page.getByRole('button', { name: 'Remove profile' }).click();
await page.getByText('No projects yet').waitFor();
const { invocations, profileId } = await page.evaluate(() => ({ invocations: window.__COLUI_MOCK_INVOCATIONS ?? [], profileId: window.__COLUI_MOCK_PROFILE_ID }));
if (!profileId) throw new Error('profile id was not recorded');
for (const command of ['apply_project', 'stop_project', 'tear_down_project', 'restart_project']) {
  const call = [...invocations].reverse().find(invocation => invocation.command === command);
  if (!call || JSON.stringify(call.args) !== JSON.stringify({ profileId })) throw new Error(`invalid ${command} payload`);
}
const remove = [...invocations].reverse().find(invocation => invocation.command === 'remove_profile');
if (!remove || JSON.stringify(remove.args) !== JSON.stringify({ profileId, expectedRevision: 2 })) throw new Error('invalid remove_profile payload');
await lifecycleContext.close();
await browser.close();
