import { firefox } from '@playwright/test';

const browser = await firefox.launch({ headless: true });
const failureContext = await browser.newContext();
const failurePage = await failureContext.newPage();
await failurePage.goto(`${process.argv[2]}/`, { waitUntil: 'networkidle' });
await failurePage.getByRole('button', { name: /add project/i }).click();
await failurePage.getByLabel('Display name').fill('Existing Project');
await failurePage.getByLabel('Compose name').fill('existing');
await failurePage.getByLabel('Working directory').fill('/tmp/existing');
await failurePage.getByRole('button', { name: 'Next' }).click();
await failurePage.getByRole('button', { name: 'Save', exact: true }).click();
await failurePage.getByText('Existing Project').waitFor();
await failurePage.goto(`${process.argv[2]}/?runtimeFailure`, { waitUntil: 'networkidle' });
await failurePage.getByText('Existing Project').waitFor();
if (!await failurePage.getByText('runtime offline').isVisible()) throw new Error('runtime failure was not visible');
await failureContext.close();
const lifecycleContext = await browser.newContext();
const page = await lifecycleContext.newPage();
await page.goto(`${process.argv[2]}/?lifecycle`, { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /add project/i }).click();
await page.getByLabel('Display name').fill('Smoke Project');
await page.getByLabel('Compose name').fill('smoke');
await page.getByLabel('Working directory').fill('/tmp/smoke');
await page.getByRole('button', { name: 'Next' }).click();
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.getByText('Smoke Project').waitFor();
await page.getByRole('link', { name: 'Diagnostics' }).click();
await page.getByRole('heading', { name: 'Diagnostics' }).waitFor();
const reconnect = page.getByRole('button', { name: 'Reconnect' });
await reconnect.click();
await reconnect.waitFor({ state: 'visible' });
await page.waitForFunction(() => [...document.querySelectorAll('button')].some(button => button.textContent === 'Reconnect' && !button.disabled));
await page.getByRole('link', { name: 'Projects' }).click();
await page.getByRole('button', { name: /edit smoke project/i }).click();
await page.getByLabel('Display name').fill('Edited Project');
await page.getByRole('button', { name: 'Next' }).click();
await page.getByRole('button', { name: 'Save', exact: true }).click();
await page.getByText('Edited Project').waitFor();
await page.getByRole('button', { name: /more actions/i }).click();
await page.getByRole('menuitem', { name: 'Remove profile' }).click();
await page.getByRole('button', { name: /^Cancel$/ }).click();
await page.getByText('Edited Project').waitFor();
const beforeRemove = await page.evaluate(() => (window.__COLUI_MOCK_INVOCATIONS ?? []).filter(invocation => invocation.command === 'remove_profile').length);
if (beforeRemove !== 0) throw new Error('remove_profile invoked while confirmation was canceled');
await page.getByRole('button', { name: /more actions/i }).click();
await page.getByRole('menuitem', { name: 'Remove profile' }).click();
await page.getByRole('button', { name: 'Remove profile' }).click();
await page.getByText('No projects yet').waitFor();
const { invocations, profileId } = await page.evaluate(() => ({ invocations: window.__COLUI_MOCK_INVOCATIONS ?? [], profileId: window.__COLUI_MOCK_PROFILE_ID }));
if (!profileId) throw new Error('profile id was not recorded');
if (!invocations.some(invocation => invocation.command === 'reconnect_runtime')) throw new Error('Diagnostics reconnect was not invoked');
const remove = [...invocations].reverse().find(invocation => invocation.command === 'remove_profile');
if (!remove || JSON.stringify(remove.args) !== JSON.stringify({ profileId, expectedRevision: 2 })) throw new Error('invalid remove_profile payload');
await lifecycleContext.close();
await browser.close();
